import { projects } from '../api.js';
import { t } from '../i18n.js';
import { renderEmpty } from '../components/empty.js';
import { escapeHtml } from '../safe-html.js';
import { toast } from '../components/toast.js';
export default { render: async (ctx) => {
  if (!ctx.activeProjectId) return `<div class="app-view-container">${renderEmpty({ title: 'No Brand Selected' })}</div>`;
  const data = await projects.getEntities(ctx.activeProjectId).catch(() => ({items:[],deleted:[]})); const items = data.items || []; const deleted = data.deleted || []; ctx._entities = items;
  return `<div class="app-view-container"><div class="view-header"><div class="view-title-group"><h1 class="view-title">${t('nav.entities', {}, 'Entities')}</h1><p class="view-desc">${t('entities.desc', {}, 'Manual review only. CiteAura does not publish or contact third-party platforms.')}</p></div><button type="button" class="btn btn-primary btn-sm" id="save-entities">${t('common.save', {}, 'Save review')}</button></div><div class="card" style="padding:0;overflow:auto"><table class="table"><caption class="sr-only">${t('entities.list', {}, 'Entity review list')}</caption><thead><tr><th>${t('entities.platform', {}, 'Platform')}</th><th>URL</th><th>${t('common.status', {}, 'Status')}</th><th>${t('entities.note', {}, 'Reviewer note')}</th><th>${t('common.action', {}, 'Action')}</th></tr></thead><tbody>${items.map((item,i)=>`<tr class="entity-row" data-index="${i}"><td>${escapeHtml(item.platform)}</td><td><input type="url" class="input entity-url" data-index="${i}" value="${escapeHtml(item.url || '')}"></td><td><select class="input entity-status" data-index="${i}">${['pending','consistent','needs_fix'].map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><input type="text" class="input entity-note" data-index="${i}" value="${escapeHtml(item.reviewer_note || '')}"></td><td>${item.source === 'citation' ? `<button type="button" class="btn btn-ghost btn-sm remove-entity">${t('common.remove', {}, 'Remove')}</button>` : ''}</td></tr>`).join('')}</tbody></table></div>${deleted.length ? `<div class="card"><h2>${t('entities.deleted', {}, 'Deleted entities')}</h2>${deleted.map(item=>`<div style="display:flex;justify-content:space-between;gap:var(--sp-3);"><span>${escapeHtml(item.url || item.id)}</span><button type="button" class="btn btn-secondary btn-sm restore-entity" data-id="${escapeHtml(item.id)}">${t('common.restore', {}, 'Restore')}</button></div>`).join('')}</div>` : ''}</div>`;
}, mounted: (ctx) => {
  document.querySelectorAll('.remove-entity').forEach((button) => button.addEventListener('click', () => button.closest('.entity-row')?.remove()));
  document.querySelectorAll('.restore-entity').forEach((button) => button.addEventListener('click', async () => { await projects.restoreEntity(ctx.activeProjectId, button.dataset.id); await ctx.reloadCurrentView(); }));
  document.getElementById('save-entities')?.addEventListener('click', async () => { const items=[...document.querySelectorAll('.entity-row')].map((row)=>{ const i=row.dataset.index; return {...(ctx._entities||{})[i], url:row.querySelector('.entity-url').value, status:row.querySelector('.entity-status').value, reviewer_note:row.querySelector('.entity-note').value}; }); await projects.saveEntities(ctx.activeProjectId, items); toast.success(t('entities.saved', {}, 'Entities saved')); });
} };
